
# For s390 the only platform supported for now is s390x-unknown-linux-gnu
# By default this platform will trying to use the startup C routines
# the configuration below should fix that.

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSTEM:console"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-args=-e __start -static -nostartfiles"]

# Because we use a custom target described in target-s390 we need to compile the core library for it
[unstable]
build-std = ["core", "compiler_builtins"]
